### ISSUE TITLE
Bug: One prototype per file rule does not recognise attribute 

### ISSUE THREAD

**Issue by pKallert** [cvette/neos-code-style#14]
In our project we are using Monocle for rapid prototyping. 
To separate the Monocle part visually we are adding the styleguide-part afterwards to the prototype. 
```
prototype(Test.Testing:Component.Footer) < prototype(Neos.Fusion:Component) {
... 
}

prototype(Test.Testing:Component.Footer).@styleguide {
... 
}
```
The linter recognizes this as a separate prototype definition, even though it technically is not.

**Comment by cvette** [comment]
Checking for Token::DOT in addition to the existing ones should fix this:
https://github.com/cvette/neos-code-style/blob/6e4d109abf0186b945a15494547fd8b4a964a36a/src/Rules/FusionRule.php#L51

**Comment by cvette** [comment]
Actually, it was Token::OBJECT_PATH_PART_TYPE :)

**Comment by markusguenther** [comment]
Thanks for adjusting that. Tested this right now and it works great :)
