### ISSUE TITLE
Comments for ignoring errors

### ISSUE THREAD

**Issue by markusguenther** [cvette/neos-code-style#17]
I would truly appreciate it if we could ignore a rule when we write a comment, for instance, to ignore the line or the following line. I take a look into the code and I guess I need to learn more about lexers and so on before I could build something like this, but wanted to add the Idea to the issue tracker.

Furthermore, I would like to see something like phpstan did.
https://phpstan.org/user-guide/ignoring-errors

Maybe @cvette has already an idea how to achieve something like that. Otherwise, I would try to dive deeper.
And Christian still has no GitHub Sponsorship offer :P

**Comment by cvette** [comment]
You can now add `// @neoscs-ignore-next-line` or `/* @neoscs-ignore-next-line */` (multi line comments won't work) to ignore the following line.

Also, by popular demand, it is now possible to send money my way ;)
